// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using VehicleManagementAPI.Data;

#nullable disable

namespace VehicleManagementAPI.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("VehicleManagementAPI.Models.Appointment", b =>
                {
                    b.Property<int>("Appointment_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Appointment_Id"));

                    b.Property<DateTime>("Service_Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Service_Time")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("User_Id")
                        .HasColumnType("integer");

                    b.Property<int>("Vehicle_Id")
                        .HasColumnType("integer");

                    b.HasKey("Appointment_Id");

                    b.HasIndex("User_Id");

                    b.HasIndex("Vehicle_Id");

                    b.ToTable("Appointments");
                });

            modelBuilder.Entity("VehicleManagementAPI.Models.Notification", b =>
                {
                    b.Property<int>("Notification_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Notification_Id"));

                    b.Property<string>("Notification_Message")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("Notification_Time")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("User_Id")
                        .HasColumnType("integer");

                    b.HasKey("Notification_Id");

                    b.HasIndex("User_Id");

                    b.ToTable("Notifications");
                });

            modelBuilder.Entity("VehicleManagementAPI.Models.Part", b =>
                {
                    b.Property<int>("Part_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Part_Id"));

                    b.Property<string>("Part_Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("Part_Price")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<int>("Stock")
                        .HasColumnType("integer");

                    b.HasKey("Part_Id");

                    b.ToTable("Parts");
                });

            modelBuilder.Entity("VehicleManagementAPI.Models.PartRequest", b =>
                {
                    b.Property<int>("Part_Request_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Part_Request_Id"));

                    b.Property<int>("Part_Id")
                        .HasColumnType("integer");

                    b.Property<DateTime>("Request_Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("User_Id")
                        .HasColumnType("integer");

                    b.HasKey("Part_Request_Id");

                    b.HasIndex("Part_Id");

                    b.HasIndex("User_Id");

                    b.ToTable("PartRequests");
                });

            modelBuilder.Entity("VehicleManagementAPI.Models.PurchaseInvoice", b =>
                {
                    b.Property<int>("Purchase_Invoice_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Purchase_Invoice_ID"));

                    b.Property<string>("Payment_Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("Purchase_Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("Total_Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<int>("Vendor_Id")
                        .HasColumnType("integer");

                    b.HasKey("Purchase_Invoice_ID");

                    b.HasIndex("Vendor_Id");

                    b.ToTable("PurchaseInvoices");
                });

            modelBuilder.Entity("VehicleManagementAPI.Models.PurchaseItem", b =>
                {
                    b.Property<int>("PurchaseItem_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("PurchaseItem_Id"));

                    b.Property<int>("Part_Id")
                        .HasColumnType("integer");

                    b.Property<decimal>("Price")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<int>("Purchase_Invoice_ID")
                        .HasColumnType("integer");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.HasKey("PurchaseItem_Id");

                    b.HasIndex("Part_Id");

                    b.HasIndex("Purchase_Invoice_ID");

                    b.ToTable("PurchaseItems");
                });

            modelBuilder.Entity("VehicleManagementAPI.Models.Quotation", b =>
                {
                    b.Property<int>("Quotation_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Quotation_Id"));

                    b.Property<int>("Appointment_Id")
                        .HasColumnType("integer");

                    b.Property<decimal>("Labor_Cost")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<DateTime>("Quotation_Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Quotation_Id");

                    b.HasIndex("Appointment_Id");

                    b.ToTable("Quotations");
                });

            modelBuilder.Entity("VehicleManagementAPI.Models.QuotationItem", b =>
                {
                    b.Property<int>("QuotationItem_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("QuotationItem_Id"));

                    b.Property<bool>("Is_Selected")
                        .HasColumnType("boolean");

                    b.Property<int>("Part_Id")
                        .HasColumnType("integer");

                    b.Property<decimal>("Price")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.Property<int>("Quotation_Id")
                        .HasColumnType("integer");

                    b.HasKey("QuotationItem_Id");

                    b.HasIndex("Part_Id");

                    b.HasIndex("Quotation_Id");

                    b.ToTable("QuotationItems");
                });

            modelBuilder.Entity("VehicleManagementAPI.Models.SalesInvoice", b =>
                {
                    b.Property<int>("Sales_Invoice_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Sales_Invoice_ID"));

                    b.Property<int?>("Appointment_Id")
                        .HasColumnType("integer");

                    b.Property<string>("Payment_Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("Sales_Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("Total_Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<int>("User_Id")
                        .HasColumnType("integer");

                    b.HasKey("Sales_Invoice_ID");

                    b.HasIndex("Appointment_Id");

                    b.HasIndex("User_Id");

                    b.ToTable("SalesInvoices");
                });

            modelBuilder.Entity("VehicleManagementAPI.Models.SalesItem", b =>
                {
                    b.Property<int>("SalesItem_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("SalesItem_Id"));

                    b.Property<int>("Part_Id")
                        .HasColumnType("integer");

                    b.Property<decimal>("Price")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.Property<int>("Sales_Invoice_ID")
                        .HasColumnType("integer");

                    b.HasKey("SalesItem_Id");

                    b.HasIndex("Part_Id");

                    b.HasIndex("Sales_Invoice_ID");

                    b.ToTable("SalesItems");
                });

            modelBuilder.Entity("VehicleManagementAPI.Models.User", b =>
                {
                    b.Property<int>("User_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("User_Id"));

                    b.Property<string>("Contact")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("User_Role")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("User_Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("VehicleManagementAPI.Models.Vehicle", b =>
                {
                    b.Property<int>("Vehicle_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Vehicle_Id"));

                    b.Property<int>("User_Id")
                        .HasColumnType("integer");

                    b.Property<string>("Vehicle_Number")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Vehicle_Type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Vehicle_Id");

                    b.HasIndex("User_Id");

                    b.ToTable("Vehicles");
                });

            modelBuilder.Entity("VehicleManagementAPI.Models.Vendor", b =>
                {
                    b.Property<int>("Vendor_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Vendor_Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Contact")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Vendor_Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Vendor_Id");

                    b.ToTable("Vendors");
                });

            modelBuilder.Entity("VehicleManagementAPI.Models.VendorItem", b =>
                {
                    b.Property<int>("VendorItem_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("VendorItem_Id"));

                    b.Property<bool>("Available")
                        .HasColumnType("boolean");

                    b.Property<int>("Part_Id")
                        .HasColumnType("integer");

                    b.Property<string>("Part_Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("Part_Price")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<int>("Vendor_Id")
                        .HasColumnType("integer");

                    b.HasKey("VendorItem_Id");

                    b.HasIndex("Part_Id");

                    b.HasIndex("Vendor_Id");

                    b.ToTable("VendorItems");
                });

            modelBuilder.Entity("VehicleManagementAPI.Models.Appointment", b =>
                {
                    b.HasOne("VehicleManagementAPI.Models.User", "User")
                        .WithMany("Appointments")
                        .HasForeignKey("User_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("VehicleManagementAPI.Models.Vehicle", "Vehicle")
                        .WithMany("Appointments")
                        .HasForeignKey("Vehicle_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");

                    b.Navigation("Vehicle");
                });

            modelBuilder.Entity("VehicleManagementAPI.Models.Notification", b =>
                {
                    b.HasOne("VehicleManagementAPI.Models.User", "User")
                        .WithMany("Notifications")
                        .HasForeignKey("User_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("VehicleManagementAPI.Models.PartRequest", b =>
                {
                    b.HasOne("VehicleManagementAPI.Models.Part", "Part")
                        .WithMany("PartRequests")
                        .HasForeignKey("Part_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("VehicleManagementAPI.Models.User", "User")
                        .WithMany("PartRequests")
                        .HasForeignKey("User_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Part");

                    b.Navigation("User");
                });

            modelBuilder.Entity("VehicleManagementAPI.Models.PurchaseInvoice", b =>
                {
                    b.HasOne("VehicleManagementAPI.Models.Vendor", "Vendor")
                        .WithMany("PurchaseInvoices")
                        .HasForeignKey("Vendor_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Vendor");
                });

            modelBuilder.Entity("VehicleManagementAPI.Models.PurchaseItem", b =>
                {
                    b.HasOne("VehicleManagementAPI.Models.Part", "Part")
                        .WithMany("PurchaseItems")
                        .HasForeignKey("Part_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("VehicleManagementAPI.Models.PurchaseInvoice", "PurchaseInvoice")
                        .WithMany("PurchaseItems")
                        .HasForeignKey("Purchase_Invoice_ID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Part");

                    b.Navigation("PurchaseInvoice");
                });

            modelBuilder.Entity("VehicleManagementAPI.Models.Quotation", b =>
                {
                    b.HasOne("VehicleManagementAPI.Models.Appointment", "Appointment")
                        .WithMany("Quotations")
                        .HasForeignKey("Appointment_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Appointment");
                });

            modelBuilder.Entity("VehicleManagementAPI.Models.QuotationItem", b =>
                {
                    b.HasOne("VehicleManagementAPI.Models.Part", "Part")
                        .WithMany("QuotationItems")
                        .HasForeignKey("Part_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("VehicleManagementAPI.Models.Quotation", "Quotation")
                        .WithMany("QuotationItems")
                        .HasForeignKey("Quotation_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Part");

                    b.Navigation("Quotation");
                });

            modelBuilder.Entity("VehicleManagementAPI.Models.SalesInvoice", b =>
                {
                    b.HasOne("VehicleManagementAPI.Models.Appointment", null)
                        .WithMany("SalesInvoices")
                        .HasForeignKey("Appointment_Id");

                    b.HasOne("VehicleManagementAPI.Models.User", "User")
                        .WithMany("SalesInvoices")
                        .HasForeignKey("User_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("VehicleManagementAPI.Models.SalesItem", b =>
                {
                    b.HasOne("VehicleManagementAPI.Models.Part", "Part")
                        .WithMany("SalesItems")
                        .HasForeignKey("Part_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("VehicleManagementAPI.Models.SalesInvoice", "SalesInvoice")
                        .WithMany("SalesItems")
                        .HasForeignKey("Sales_Invoice_ID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Part");

                    b.Navigation("SalesInvoice");
                });

            modelBuilder.Entity("VehicleManagementAPI.Models.Vehicle", b =>
                {
                    b.HasOne("VehicleManagementAPI.Models.User", "User")
                        .WithMany("Vehicles")
                        .HasForeignKey("User_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("VehicleManagementAPI.Models.VendorItem", b =>
                {
                    b.HasOne("VehicleManagementAPI.Models.Part", "Part")
                        .WithMany("VendorItems")
                        .HasForeignKey("Part_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("VehicleManagementAPI.Models.Vendor", "Vendor")
                        .WithMany("VendorItems")
                        .HasForeignKey("Vendor_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Part");

                    b.Navigation("Vendor");
                });

            modelBuilder.Entity("VehicleManagementAPI.Models.Appointment", b =>
                {
                    b.Navigation("Quotations");

                    b.Navigation("SalesInvoices");
                });

            modelBuilder.Entity("VehicleManagementAPI.Models.Part", b =>
                {
                    b.Navigation("PartRequests");

                    b.Navigation("PurchaseItems");

                    b.Navigation("QuotationItems");

                    b.Navigation("SalesItems");

                    b.Navigation("VendorItems");
                });

            modelBuilder.Entity("VehicleManagementAPI.Models.PurchaseInvoice", b =>
                {
                    b.Navigation("PurchaseItems");
                });

            modelBuilder.Entity("VehicleManagementAPI.Models.Quotation", b =>
                {
                    b.Navigation("QuotationItems");
                });

            modelBuilder.Entity("VehicleManagementAPI.Models.SalesInvoice", b =>
                {
                    b.Navigation("SalesItems");
                });

            modelBuilder.Entity("VehicleManagementAPI.Models.User", b =>
                {
                    b.Navigation("Appointments");

                    b.Navigation("Notifications");

                    b.Navigation("PartRequests");

                    b.Navigation("SalesInvoices");

                    b.Navigation("Vehicles");
                });

            modelBuilder.Entity("VehicleManagementAPI.Models.Vehicle", b =>
                {
                    b.Navigation("Appointments");
                });

            modelBuilder.Entity("VehicleManagementAPI.Models.Vendor", b =>
                {
                    b.Navigation("PurchaseInvoices");

                    b.Navigation("VendorItems");
                });
#pragma warning restore 612, 618
        }
    }
}
